apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-graphql-deployment
  labels:
    app: category-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-graphql
  template:
    metadata:
      labels:
        app: category-graphql
    spec:
      containers:
      - name: category-graphql
        image: vinodhcse/category-graphql-service2:latest
        ports:
        - containerPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: category-graphql-service
spec:
  type: NodePort
  selector:
    app: category-graphql
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30401