apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-graphql-deployment
  labels:
    app: content-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-graphql
  template:
    metadata:
      labels:
        app: content-graphql
    spec:
      containers:
      - name: content-graphql
        image: vinodhcse/content-graphql-service:latest
        ports:
        - containerPort: 4002

---
apiVersion: v1
kind: Service
metadata:
  name: content-graphql-service
spec:
  type: NodePort
  selector:
    app: content-graphql
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
      nodePort: 30402