apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-graphql-deployment
  labels:
    app: gateway-graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-graphql
  template:
    metadata:
      labels:
        app: gateway-graphql
    spec:
      containers:
      - name: gateway-graphql
        image: vinodhcse/gateway-graphql-service:latest
        ports:
        - containerPort: 4002

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-graphql-service
spec:
  type: NodePort
  selector:
    app: gateway-graphql
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400